### ISSUE TITLE
Displaces Bookmarks toolbar 

### ISSUE THREAD

**Issue by ineuw** [piroor/tabsonbottom#10]
In versions 36 and 37 beta5, it forces the Bookmarks toolbar to be above the address bar in XUbuntu. In Windows 7 it seems to work so far with 37 beta 5.

**Comment by rdge** [comment]
"Bookmarks toolbar" moves to top of window (above address bar) when tabsonbottom is activated.   (FF version 48.0.2 with Mac OS 10.8.5)    Please fix! Can't use until problem is resolved. Thank you!

**Comment by rdge** [comment]
Bookmarks toolbar changes position  from normal below address toolbar to above address toolbar.   Please fix this bug to make your add-on work properly. Thanks. 

![tabsonbottom activated](https://cloud.githubusercontent.com/assets/26029241/23333740/b6a3e9ec-fb45-11e6-9663-93bfa10ddf4b.png)
![what s supposed to happen](https://cloud.githubusercontent.com/assets/26029241/23333742/c5126224-fb45-11e6-8058-5fbf750527c8.png)

**Comment by ineuw** [comment]
rdge, this is no longer an issue in Windows or Linux with versions 50 and greater. Perhaps you can update the firefox version.
