### ISSUE TITLE
FF 44 - tabs moved to top

### ISSUE THREAD

**Issue by rjameson3** [piroor/tabsonbottom#13]
Will there be any v44 support - I know it is early, but I loaded the current beta and it does not work.

thx

**Comment by Barfolomew** [comment]
Yup. Same here. Hoping for a speedy update and thanks for doing what FF was too stupid to do.

**Comment by SmilingFox** [comment]
I have the same problem since today. Hope there is a quick fix, I love this add-on!

**Comment by jbacinti** [comment]
Just upgraded to FF 44 and Tabs went to top.  When will this be fixed?

**Comment by jdanield** [comment]
same here. ready to help testing if necessary :-)

**Comment by SmilingFox** [comment]
Working again! :) Thanks for fixing ToB! Have a nice weekend!
