### ISSUE TITLE
FireFox 44...Tabs on Bottom is r/s

### ISSUE THREAD

**Issue by Condobloke** [piroor/tabsonbottom#15]
That means it does not work....at all
Tabs have relocated to top....my routine is in tatters

Please..?....Fix it !?

**Comment by NooN50** [comment]
Tabs on Bottom 0.7.1  not working 
with 
FFox 46.0.1

ANY SOLUTION ?

**Comment by Condobloke** [comment]
22nd May 2016.......fixed.
I use ...
TABS ON BOTTOM 0.7.1    (Add On)
I am using Firefox 46.0.1 in Linux Mint

**Comment by NooN50** [comment]
@Condobloke 
"_22nd May 2016.......fixed._" 
How do you mean ?
Does not work in Windows....

**Comment by Condobloke** [comment]
Works fine for me.
You may have another add on that it is not compatible with.

**Comment by Condobloke** [comment]
Try disabling all other add ons and just running Tabs On Bottom...

**Comment by NooN50** [comment]
Tnx for your reply.

Got it working with Tab Mix Plus Options again.
