### ISSUE TITLE
Double click to open new tab will maximise window since Nightly 2016-02-01

### ISSUE THREAD

**Issue by Fanolian** [piroor/tabsonbottom#16]
Steps to reproduce:
1. Install Tabs on Bottom nightly and Tree Style Tab nightly. v0.5.1 does not work on Nightly
2. Double click on the blank area of tab bar a few times.

Actual result:
Nightly window will maximise or restore its size. A new tab is opened as expected.

Expected result:
Tabs on bottom should block the resizing of window like in previous builds.

From Mozregression:
Last good Nightly: 2016-01-31
First bad Nightly: 2016-02-01
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=b2a3dc4b161fdfac6db78cc5bbfb1f53a383b65a&tochange=941033a51983ddec2d99aa9f868a54c0196a4075

Further bisection:
https://hg.mozilla.org/integration/fx-team/pushloghtml?fromchange=be27e36ce427df475b3ff827d8c0258c1c34c5b5&tochange=a67a25a5af7446d8ae9beb453bcfa12be368fcef
Regressed by [Bug 1241275](https://bugzilla.mozilla.org/show_bug.cgi?id=1241275) or [Bug 1219215](https://bugzilla.mozilla.org/show_bug.cgi?id=1219215)

Workaround:
Disable the feature in Tabs on Bottom's option. Double-clicking tab bar does not resize window. No new tabs will be opened though.

**Comment by piroor** [comment]
Thanks a lot! The commit 2cdf0fbbbbfebaa23b291a2150e6077358d44364 fixes the problem for me.

**Comment by Fanolian** [comment]
Confirm fixed on 0.6.2016020400a003940 but not 0.6release. Thanks.
